
--Structural validation: one override row per key
--Should return ZERO rows
SELECT
  RETAILER,
  RETAILER_ITEM_ID,
  ITEM_ID_AT_WEEK,
  WEEK_ENDING,
  SCENARIO,
  COUNT(*) AS ROW_COUNT
FROM DJUS_ML_SANDBOX.PUBLIC.LADDER_PLAN_OVERRIDES
GROUP BY
  RETAILER,
  RETAILER_ITEM_ID,
  ITEM_ID_AT_WEEK,
  WEEK_ENDING,
  SCENARIO
HAVING COUNT(*) > 1;

--Scenario integrity validation
-- Should return ZERO rows
SELECT *
FROM DJUS_ML_SANDBOX.PUBLIC.LADDER_PLAN_OVERRIDES o
LEFT JOIN DJUS_ML_SANDBOX.PUBLIC.LADDER_SCENARIO_CONFIG c
  ON o.SCENARIO = c.SCENARIO_CODE
WHERE c.SCENARIO_CODE IS NULL;

--Date window validation
WITH bounds AS (
  SELECT
    MIN(week_beg_date) AS START_BEG,
    MAX(week_ending)   AS END_END
  FROM DJUS_ML_SANDBOX.PUBLIC.V_LADDER_ACTIVE_SCENARIO_WEEKS
)
SELECT o.*
FROM DJUS_ML_SANDBOX.PUBLIC.LADDER_PLAN_OVERRIDES o
CROSS JOIN bounds b
WHERE o.WEEK_ENDING < b.START_BEG
   OR o.WEEK_ENDING > b.END_END;


--Business-rule validation: negative plans
SELECT *
FROM DJUS_ML_SANDBOX.PUBLIC.LADDER_PLAN_OVERRIDES
WHERE PLAN_UNITS < 0
   OR SUGGESTED_PLAN_UNITS < 0;


--Ripple sanity check
SELECT
  RETAILER,
  RETAILER_ITEM_ID,
  ITEM_ID_AT_WEEK,
  RETAIL_YEAR,
  RETAIL_WEEK,
  PLAN_UNIT_INVENTORY,
  SUGGESTED_PLAN_UNIT_INVENTORY
FROM DJUS_ML_SANDBOX.PUBLIC.LADDER_PLAN_BI_UI
WHERE PLAN_UNIT_INVENTORY < -100
   OR SUGGESTED_PLAN_UNIT_INVENTORY < -100
ORDER BY RETAILER, RETAILER_ITEM_ID, RETAIL_YEAR, RETAIL_WEEK;


--Orphan detection
SELECT o.*
FROM DJUS_ML_SANDBOX.PUBLIC.LADDER_PLAN_OVERRIDES o
LEFT JOIN DJUS_ML_SANDBOX.PUBLIC.TR3_WEEKLY_UNIFIED t
  ON t.RETAILER = o.RETAILER
 AND t.RETAILER_ITEM_ID = o.RETAILER_ITEM_ID
 AND t.WEEK_ENDING = o.WEEK_ENDING
WHERE t.RETAILER IS NULL;


--Autosave correctness validation
-- Step 1: write an override
CALL SP_LADDER_AUTOSAVE_CELL_PY(
  'Walmart',
  'TEST_ITEM',
  'TEST_DOREL',
  '2026-02-08',
  'PLAN_UNITS',
  123,
  'svc_automation'
);

-- Step 2: confirm override exists
SELECT *
FROM DJUS_ML_SANDBOX.PUBLIC.LADDER_PLAN_OVERRIDES
WHERE RETAILER = 'Walmart'
  AND RETAILER_ITEM_ID = 'TEST_ITEM'
  AND WEEK_ENDING = '2026-02-08';

-- Step 3: confirm UI view reflects it
SELECT PLAN_UNITS
FROM DJUS_ML_SANDBOX.PUBLIC.LADDER_PLAN_BI_UI
WHERE RETAILER = 'Walmart'
  AND RETAILER_ITEM_ID = 'TEST_ITEM'
  AND WEEK_ENDING = '2026-02-08';
